apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4K
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW5fcGFzc3dvcmQK
  PROXY_ADDRESS_FORWARDING: dHJ1ZQo=
  DB_VENDOR: UE9TVEdSRVMK
  DB_ADDR: cG9zdGdyZXMtZGIK
  DB_PORT: NTQzMgo=
  DB_DATABASE: a2V5Y2xvYWsK
  DB_PASSWORD: YWRtaW5wZwo=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  labels:
    app: postgresql-db
data:
  POSTGRES_DB: a2V5Y2xvYWsK
  POSTGRES_USER: YWRtaW4K
  POSTGRES_PASSWORD: YWRtaW5wZwo=
  PGDATA: L2RhdGEvcGdkYXRhCg==

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  AUTH_PART_MONGO: YWRtaW4=
  MONGO_INITDB_DATABASE: dXBsb2FkZXI=
  MONGO_INITDB_ROOT_PASSWORD: YWljMVV5b2g0dnVhMWll
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_HOST: bW9uZ29kYg==
  DB_PORT: MjcwMTc=

---
apiVersion: v1
kind: Secret
metadata:
  name: uploader-mongo-secret
data:
  AUTH_PART_MONGO: YWRtaW4=
  MONGO_INITDB_DATABASE: dXBsb2FkZXI=
  MONGO_INITDB_ROOT_PASSWORD: dXBsb2FkZXItcGFzc3dk
  MONGO_INITDB_ROOT_USERNAME: dXBsb2FkZXI=
  MONGO_HOST: bW9uZ29kYg==
  DB_PORT: MjcwMTc=
